build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "conan-arduino-toolchain/1.0.0"
    CONAN_UPLOAD: "https://api.bintray.com/conan/anton-matosov/general"
    CONAN_USERNAME: "anton-matosov"
    CONAN_LOGIN_USERNAME: "anton-matosov"
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install git+https://github.com/anton-matosov/conan.git --upgrade
  - pip.exe install git+https://github.com/anton-matosov/conan_package_tools.git
  - conan user # It creates the conan data directory

test_script:
  - python build.py
